language: java
cache:
  directories:
  - $HOME/.m2
  - node_modules
  email:
    recipients:
      - duotayct@gmail.com
      - leethiamchye@gmail.com
      - metamagpie@gmail.com
      - neojunjie87@gmail.com
      - shaojieyew@gmail.com
      - yowchenglim+dev@gmail.com
    on_success: never
    on_failure: always
jobs:
  include:
    - stage: ecr_deploy
      sudo: required #is required to use docker service in travis
      script: mvn clean package -P dockerize
      services:
        - docker
      after_success:
        - docker --version  # document the version travis is using
        - pip install --user awscli # install aws cli w/o sudo
        - export PATH=$PATH:$HOME/.local/bin # put aws in the path
        - eval $(aws ecr get-login --no-include-email --region ap-southeast-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
        - docker load --input target/jib-image.tar
        - docker tag gem 037562003025.dkr.ecr.ap-southeast-1.amazonaws.com/docker-repo:gem
        - docker push 037562003025.dkr.ecr.ap-southeast-1.amazonaws.com/docker-repo:gem
# stages:
#   - name: ecr_deploy
#     # require the branch name to be master (note for PRs this is the base branch name)
#     if: branch = master