language: java
notifications:
  email:
    recipients:
      - duotayct@gmail.com
      - leethiamchye@gmail.com
      - metamagpie@gmail.com
      - neojunjie87@gmail.com
      - shaojieyew@gmail.com
      - yowcheng.lim@gmail.com
    on_success: never
    on_failure: always