language: java
script: mvn clean package -P $TRAVIS_BRANCH
notifications:
  email:
    recipients:
      - duotayct@gmail.com
      - leethiamchye@gmail.com
      - metamagpie@gmail.com
      - neojunjie87@gmail.com
      - shaojieyew@gmail.com
      - yowchenglim+dev@gmail.com
    on_success: never
    on_failure: always
sudo: required #is required to use docker service in travis
services:
  - docker
after_success:
  - test $TRAVIS_BRANCH = "master" && docker --version  # document the version travis is using
  - test $TRAVIS_BRANCH = "master" && pip install --user awscli # install aws cli w/o sudo
  - test $TRAVIS_BRANCH = "master" && export PATH=$PATH:$HOME/.local/bin # put aws in the path
  - test $TRAVIS_BRANCH = "master" && eval $(aws ecr get-login --no-include-email --region ap-southeast-1) #needs AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY envvars
  - test $TRAVIS_BRANCH = "master" && docker load --input target/jib-image.tar
  - test $TRAVIS_BRANCH = "master" && docker tag gem 037562003025.dkr.ecr.ap-southeast-1.amazonaws.com/docker-repo:gem
  - test $TRAVIS_BRANCH = "master" && docker push 037562003025.dkr.ecr.ap-southeast-1.amazonaws.com/docker-repo:gem